In [35]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
import pandas as pd
import numpy as np

### Step 1: Data preparation

In [37]:
NBAmod = pd.read_excel("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 3 - Prediction Models with Sports Data/Week 4 Content/Week 4 Assignment/NBA prediction model (Assignment).xlsx")
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434

In [38]:
# Define variables for the probabilities of a home win and away win associated with bookmaker odds
NBAmod['hwinprob']= 1/(NBAmod['hwinodds'])/(1/(NBAmod['hwinodds'])+ 1/(NBAmod['hloseodds']))
NBAmod['awinprob']= 1/(NBAmod['hloseodds'])/(1/(NBAmod['hloseodds'])+ 1/(NBAmod['hwinodds']))
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,0.171852
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,0.232342
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,0.388614
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,0.201342
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,0.113089

In [39]:
# Define a dummy variable = 1 if the home team loses, and zero otherwise
NBAmod['hlose'] = np.where(NBAmod['hwin'] == 1, 0 , 1)
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob,hlose
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,0.171852,0
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412,0
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,0.232342,0
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000,0
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831,0
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,0.388614,0
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,0.201342,0
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277,0
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,0.113089,0

In [40]:
# Define a variable equal to H if the home team wins and A if the visiting team wins
NBAmod['winner'] = np.where(NBAmod['hwin'] == 1, 'H' , 'A')
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob,hlose,winner
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,0.171852,0,H
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412,0,H
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,0.232342,0,H
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000,0,H
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774,0,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831,0,H
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,0.388614,0,H
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,0.201342,0,H
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277,0,H
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,0.113089,0,H

In [41]:
# Define a variable equal to H if the home team win probability is greater than 0.5 according to the bookmaker odds and A otherwise
NBAmod['winpred'] = np.where(NBAmod['hwinprob'] >= .5,'H','A')
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,0.171852,0,H,H
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412,0,H,H
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,0.232342,0,H,H
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000,0,H,H
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774,0,H,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831,0,H,A
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,0.388614,0,H,H
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,0.201342,0,H,H
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277,0,H,H
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,0.113089,0,H,H

In [42]:
# Define a variable equal to the logarithm of the ratio of the home team salaries to the visiting team salaries.
NBAmod['lTSratio'] = np.log(NBAmod['hteamsal']/NBAmod['opposal'])
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred,lTSratio
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,0.171852,0,H,H,0.419270
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412,0,H,H,0.419270
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,0.232342,0,H,H,0.390218
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000,0,H,H,0.390218
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774,0,H,H,0.325775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831,0,H,A,-0.323308
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,0.388614,0,H,H,-0.004293
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,0.201342,0,H,H,0.026538
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277,0,H,H,0.026538
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,0.113089,0,H,H,-0.105252

### Step 2: Estimate a logit model of home time wins depending on the log salary ratio, using the data for calendar year 2018 as the “training data”.

In [43]:
# Define a subset for the calendar year 2018 data
NBAmod_2018 = NBAmod[NBAmod['year']==2018]
NBAmod_2018

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred,lTSratio
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,0.129412,0,H,H,0.419270
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,0.280000,0,H,H,0.390218
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,0.143774,0,H,H,0.325775
5,Charlotte Hornets,Atlanta Hawks,29,11,2018,1.11,7.08,108,94,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.864469,0.135531,0,H,H,0.325775
8,Cleveland Cavaliers,Atlanta Hawks,22,10,2018,1.26,3.97,111,133,0,Cleveland Cavaliers - Atlanta Hawks,0,125587784,83389484,0.759082,0.240918,1,A,H,0.409483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,Orlando Magic,Washington Wizards,10,11,2018,2.46,1.58,117,108,0,Orlando Magic - Washington Wizards,1,107918996,130318434,0.391089,0.608911,0,H,A,-0.188600
1222,Philadelphia 76ers,Washington Wizards,1,12,2018,1.23,4.27,123,98,0,Philadelphia 76ers - Washington Wizards,1,105609165,130318434,0.776364,0.223636,0,H,H,-0.210236
1224,Portland Trail Blazers,Washington Wizards,23,10,2018,1.51,2.65,124,125,1,Portland Trail Blazers - Washington Wizards,0,131666204,130318434,0.637019,0.362981,1,A,H,0.010289
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0.650831,0,H,A,-0.323308
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,0.180277,0,H,H,0.026538

In [44]:
# Import the logistic regression package
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [45]:
# Run the logistic regression of hwin on the log salary ratio
hwin_Lg = 'hwin~lTSratio'
model = smf.glm(formula = hwin_Lg, data = NBAmod_2018, family=sm.families.Binomial())
result = model.fit()
print(result.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   hwin   No. Observations:                  542
Model:                            GLM   Df Residuals:                      540
Model Family:                Binomial   Df Model:                            1
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -359.61
Date:                Tue, 25 Aug 2026   Deviance:                       719.21
Time:                        22:24:37   Pearson chi2:                     543.
No. Iterations:                     4   Pseudo R-squ. (CS):            0.01149
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4452      0.089      5.026      0.000       0.272       0.619
lTSratio       1.1216      0.452      2.482      0.013       0.236       2.007
==============================================================================

### Step 3: Define the predicted probabilities and the predicted results, using the entire data set

In [46]:
# Calculate the predicted probability of home win
NBAmod['pred_Home_W'] = 1/(1+np.exp(-(0.4452 + 1.1216*NBAmod['lTSratio'])))
display(NBAmod)

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hwin,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred,lTSratio,pred_Home_W
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,1,126822990,83389484,0.828148,0.171852,0,H,H,0.419270,0.714115
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,...,1,126822990,83389484,0.870588,0.129412,0,H,H,0.419270,0.714115
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,1,123191458,83389484,0.767658,0.232342,0,H,H,0.390218,0.707416
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,...,1,123191458,83389484,0.720000,0.280000,0,H,H,0.390218,0.707416
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,...,1,115503070,83389484,0.856226,0.143774,0,H,H,0.325775,0.692235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,...,1,94318099,130318434,0.349169,0.650831,0,H,A,-0.323308,0.520633
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,1,129760213,130318434,0.611386,0.388614,0,H,H,-0.004293,0.608351
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,1,133823098,130318434,0.798658,0.201342,0,H,H,0.026538,0.616558
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,...,1,133823098,130318434,0.819723,0.180277,0,H,H,0.026538,0.616558
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,1,117299328,130318434,0.886911,0.113089,0,H,H,-0.105252,0.581066

In [47]:
# Based on the predicted probability, define the predicted result H as the outcome where the predicted home win probability is greater than 0.5, and A otherwise.
NBAmod['mod_win_pred'] =  np.where(NBAmod['pred_Home_W'] >= .5,'H','A')
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred,lTSratio,pred_Home_W,mod_win_pred
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,126822990,83389484,0.828148,0.171852,0,H,H,0.419270,0.714115,H
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,...,126822990,83389484,0.870588,0.129412,0,H,H,0.419270,0.714115,H
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,123191458,83389484,0.767658,0.232342,0,H,H,0.390218,0.707416,H
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,...,123191458,83389484,0.720000,0.280000,0,H,H,0.390218,0.707416,H
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,...,115503070,83389484,0.856226,0.143774,0,H,H,0.325775,0.692235,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,...,94318099,130318434,0.349169,0.650831,0,H,A,-0.323308,0.520633,H
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,129760213,130318434,0.611386,0.388614,0,H,H,-0.004293,0.608351,H
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,133823098,130318434,0.798658,0.201342,0,H,H,0.026538,0.616558,H
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,...,133823098,130318434,0.819723,0.180277,0,H,H,0.026538,0.616558,H
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,117299328,130318434,0.886911,0.113089,0,H,H,-0.105252,0.581066,H

### Step 4: For games played in 2019, compare the bookmaker probabilities and model probabilities in terms of the mean number of successfully predicted outcomes and the Brier scores.

In [48]:
# Define the subset of games played in calendar year 2019
NBAmod_2019 = NBAmod[NBAmod['year']==2019]
NBAmod_2019

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hteamsal,opposal,hwinprob,awinprob,hlose,winner,winpred,lTSratio,pred_Home_W,mod_win_pred
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,126822990,83389484,0.828148,0.171852,0,H,H,0.419270,0.714115,H
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,123191458,83389484,0.767658,0.232342,0,H,H,0.390218,0.707416,H
6,Chicago Bulls,Atlanta Hawks,3,3,2019,1.56,2.50,118,123,0,...,103043494,83389484,0.615764,0.384236,1,A,H,0.211629,0.664311,H
7,Chicago Bulls,Atlanta Hawks,24,1,2019,1.83,2.02,101,121,0,...,103043494,83389484,0.524675,0.475325,1,A,H,0.211629,0.664311,H
14,Houston Rockets,Atlanta Hawks,26,2,2019,1.09,7.99,119,111,0,...,134244543,83389484,0.879956,0.120044,0,H,H,0.476141,0.726957,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,Philadelphia 76ers,Washington Wizards,9,1,2019,1.28,3.80,132,115,0,...,105609165,130318434,0.748031,0.251969,0,H,H,-0.210236,0.552159,H
1223,Phoenix Suns,Washington Wizards,28,3,2019,2.00,1.85,121,124,0,...,103593896,130318434,0.480519,0.519481,1,A,A,-0.229503,0.546810,H
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,129760213,130318434,0.611386,0.388614,0,H,H,-0.004293,0.608351,H
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,133823098,130318434,0.798658,0.201342,0,H,H,0.026538,0.616558,H
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,117299328,130318434,0.886911,0.113089,0,H,H,-0.105252,0.581066,H

In [49]:
# Define a dummy variable equal to 1 when the bookmaker result prediction is correct, and zero otherwise. Define the equivalent variable for the logit model prediction.
NBAmod_2019['BMcorrect'] = np.where(NBAmod_2019['winpred'] == NBAmod_2019['winner'], 1, 0)
NBAmod_2019['Modcorrect'] = np.where(NBAmod_2019['mod_win_pred'] == NBAmod_2019['winner'], 1, 0)
NBAmod_2019

/tmp/ipykernel_960/3741162610.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NBAmod_2019['BMcorrect'] = np.where(NBAmod_2019['winpred'] == NBAmod_2019['winner'], 1, 0)
/tmp/ipykernel_960/3741162610.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NBAmod_2019['Modcorrect'] = np.where(NBAmod_2019['mod_win_pred'] == NBAmod_2019['winner'], 1, 0)

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hwinprob,awinprob,hlose,winner,winpred,lTSratio,pred_Home_W,mod_win_pred,BMcorrect,Modcorrect
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,0.828148,0.171852,0,H,H,0.419270,0.714115,H,1,1
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,0.767658,0.232342,0,H,H,0.390218,0.707416,H,1,1
6,Chicago Bulls,Atlanta Hawks,3,3,2019,1.56,2.50,118,123,0,...,0.615764,0.384236,1,A,H,0.211629,0.664311,H,0,0
7,Chicago Bulls,Atlanta Hawks,24,1,2019,1.83,2.02,101,121,0,...,0.524675,0.475325,1,A,H,0.211629,0.664311,H,0,0
14,Houston Rockets,Atlanta Hawks,26,2,2019,1.09,7.99,119,111,0,...,0.879956,0.120044,0,H,H,0.476141,0.726957,H,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,Philadelphia 76ers,Washington Wizards,9,1,2019,1.28,3.80,132,115,0,...,0.748031,0.251969,0,H,H,-0.210236,0.552159,H,1,1
1223,Phoenix Suns,Washington Wizards,28,3,2019,2.00,1.85,121,124,0,...,0.480519,0.519481,1,A,A,-0.229503,0.546810,H,1,0
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,0.611386,0.388614,0,H,H,-0.004293,0.608351,H,1,1
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,0.798658,0.201342,0,H,H,0.026538,0.616558,H,1,1
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,0.886911,0.113089,0,H,H,-0.105252,0.581066,H,1,1

In [50]:
# Mean of BMcorrect (Bookmaker prediction success rate)
NBAmod_2019['BMcorrect'].mean()

np.float64(0.6918604651162791)

In [51]:
# Mean of Modcorrect (Model prediction success rate)
NBAmod_2019['Modcorrect'].mean()

np.float64(0.5872093023255814)

In [52]:
# Define the Brier score for the bookmaker probabilities and the Brier score for the logit model probabilities
NBAmod_2019['BrierBM']= (NBAmod_2019['hwinprob']-NBAmod_2019['hwin'])**2 + (NBAmod_2019['awinprob']-NBAmod_2019['hlose'])**2
NBAmod_2019['BrierMod'] = (NBAmod_2019['pred_Home_W'] - NBAmod_2019['hwin'])**2 + ((1-NBAmod_2019['pred_Home_W'])-NBAmod_2019['hlose'])**2

/tmp/ipykernel_960/3800473669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NBAmod_2019['BrierBM']= (NBAmod_2019['hwinprob']-NBAmod_2019['hwin'])**2 + (NBAmod_2019['awinprob']-NBAmod_2019['hlose'])**2
/tmp/ipykernel_960/3800473669.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NBAmod_2019['BrierMod'] = (NBAmod_2019['pred_Home_W'] - NBAmod_2019['hwin'])**2 + ((1-NBAmod_2019['pred_Home_W'])-NBAmod_2019['hlose'])**2

In [53]:
# Mean of BrierBM (Bookmaker Brier score)
NBAmod_2019['BrierBM'].mean()

np.float64(0.3939058021238843)

In [54]:
# Mean of BrierModel (Model Brier score)
NBAmod_2019['BrierMod'].mean()

np.float64(0.4768713411427079)