In [ ]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# load the data

NBA19 = pd.read_excel("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 3 - Prediction Models with Sports Data/Week 2 Content/Week 2 Assignment/NBA2019odds.xlsx")
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win
0,Atlanta Hawks,New York Knicks,18,10,2018,2.39,1.60,107,126,0,0,New York Knicks - Atlanta Hawks,126:107,0
1,Atlanta Hawks,Memphis Grizzlies,20,10,2018,3.34,1.34,117,131,0,0,Memphis Grizzlies - Atlanta Hawks,131:117,0
2,Atlanta Hawks,Cleveland Cavaliers,22,10,2018,3.97,1.26,133,111,0,0,Cleveland Cavaliers - Atlanta Hawks,111:133,1
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Washington Wizards,Denver Nuggets,1,4,2019,5.68,1.15,95,90,0,0,Denver Nuggets - Washington Wizards,90:95,1
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0
2458,Washington Wizards,New York Knicks,8,4,2019,1.58,2.44,110,113,0,0,New York Knicks - Washington Wizards,113:110,0
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0

In [ ]:
# Calculate the implied win probability based on the bookmaker odds
NBA19['winprob']= 1/(NBA19['winodds'])/(1/(NBA19['winodds'])+ 1/(NBA19['loseodds']))
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
0,Atlanta Hawks,New York Knicks,18,10,2018,2.39,1.60,107,126,0,0,New York Knicks - Atlanta Hawks,126:107,0,0.401003
1,Atlanta Hawks,Memphis Grizzlies,20,10,2018,3.34,1.34,117,131,0,0,Memphis Grizzlies - Atlanta Hawks,131:117,0,0.286325
2,Atlanta Hawks,Cleveland Cavaliers,22,10,2018,3.97,1.26,133,111,0,0,Cleveland Cavaliers - Atlanta Hawks,111:133,1,0.240918
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Washington Wizards,Denver Nuggets,1,4,2019,5.68,1.15,95,90,0,0,Denver Nuggets - Washington Wizards,90:95,1,0.168375
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0,0.807754
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0,0.298475
2458,Washington Wizards,New York Knicks,8,4,2019,1.58,2.44,110,113,0,0,New York Knicks - Washington Wizards,113:110,0,0.606965
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0,0.637019

In [ ]:
# Drop from the data all games for which home = 0
NBA19 = NBA19[NBA19['home'] != 0]
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
7,Atlanta Hawks,Sacramento Kings,2,11,2018,2.16,1.73,115,146,0,1,Atlanta Hawks - Sacramento Kings,115:146,0,0.444730
8,Atlanta Hawks,Miami Heat,4,11,2018,2.91,1.43,123,118,0,1,Atlanta Hawks - Miami Heat,123:118,1,0.329493
10,Atlanta Hawks,New York Knicks,8,11,2018,2.00,1.83,107,112,0,1,Atlanta Hawks - New York Knicks,107:112,0,0.477807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,Washington Wizards,Denver Nuggets,22,3,2019,4.06,1.26,108,113,0,1,Washington Wizards - Denver Nuggets,108:113,0,0.236842
2451,Washington Wizards,Miami Heat,24,3,2019,1.83,2.02,108,113,0,1,Washington Wizards - Miami Heat,108:113,0,0.524675
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0,0.807754
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0,0.298475
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0,0.637019

In [ ]:
# What is the correlation between the home team win probability and home team wins across the entire 2018/19 season?
np.corrcoef(NBA19["winprob"], NBA19['win'])

array([[1.        , 0.39652887],
       [0.39652887, 1.        ]])

Then create the following subsets

a.	One for games where the absolute value of the points difference is less than 9 and another for games where the points difference is greater than 9 (9 is the median points difference in the data)

b.	One for games that went to overtime, and one for games which finished in regulation time

c.	One for games played in calendar year 2018, one for games played in calendar year 2019

d.	One for each month in the data (October to April)

In [ ]:
#a
NBA19_Less_Median =NBA19[abs(NBA19['teampts'] - NBA19['oppopts'])< 9]
NBA19_Greater_Median =  NBA19[abs(NBA19['teampts'] - NBA19['oppopts'])> 9]
NBA19_Less_Median

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
8,Atlanta Hawks,Miami Heat,4,11,2018,2.91,1.43,123,118,0,1,Atlanta Hawks - Miami Heat,123:118,1,0.329493
10,Atlanta Hawks,New York Knicks,8,11,2018,2.00,1.83,107,112,0,1,Atlanta Hawks - New York Knicks,107:112,0,0.477807
16,Atlanta Hawks,Los Angeles Clippers,20,11,2018,3.26,1.36,119,127,0,1,Atlanta Hawks - Los Angeles Clippers,119:127,0,0.294372
19,Atlanta Hawks,Charlotte Hornets,26,11,2018,3.30,1.35,124,123,0,1,Atlanta Hawks - Charlotte Hornets,124:123,1,0.290323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,Washington Wizards,Memphis Grizzlies,17,3,2019,1.81,2.04,135,128,0,1,Washington Wizards - Memphis Grizzlies,135:128,1,0.529870
2450,Washington Wizards,Denver Nuggets,22,3,2019,4.06,1.26,108,113,0,1,Washington Wizards - Denver Nuggets,108:113,0,0.236842
2451,Washington Wizards,Miami Heat,24,3,2019,1.83,2.02,108,113,0,1,Washington Wizards - Miami Heat,108:113,0,0.524675
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0,0.807754
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0,0.637019

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the points difference was less than 9?
np.corrcoef(NBA19_Less_Median["winprob"], NBA19_Less_Median['win'])

array([[1.        , 0.19811648],
       [0.19811648, 1.        ]])

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the points difference was greater than 9?
np.corrcoef(NBA19_Greater_Median["winprob"], NBA19_Greater_Median['win'])

array([[1.        , 0.57647206],
       [0.57647206, 1.        ]])

From these correlations we can assume that uncertain games are the ones where the bookmakers odds are most likely to be wrong and the scores are likely to be the closest.  Games with a low point differential between a huge favorite and a huge underdog might not even make it possible for the favorite to cover a game.  These factors are what makes any sports only forecastable to a certain degree as there are random underlying factors that could just pop up on any given night.

In [ ]:
#b
NBA19_Overtime = NBA19[NBA19['overtime'] != 0]
NBA19_Regulation =  NBA19[NBA19['overtime'] == 0]
NBA19_Overtime

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
61,Atlanta Hawks,Minnesota Timberwolves,28,2,2019,2.69,1.49,131,123,1,1,Atlanta Hawks - Minnesota Timberwolves,131:123 ET,1,0.356459
62,Atlanta Hawks,Chicago Bulls,2,3,2019,1.90,1.93,161,168,1,1,Atlanta Hawks - Chicago Bulls,161:168 ET,0,0.503916
76,Atlanta Hawks,Milwaukee Bucks,31,3,2019,2.19,1.72,136,135,1,1,Atlanta Hawks - Milwaukee Bucks,136:135 ET,1,0.439898
96,Boston Celtics,Toronto Raptors,17,11,2018,1.78,2.08,123,116,1,1,Boston Celtics - Toronto Raptors,123:116 ET,1,0.538860
114,Boston Celtics,Philadelphia 76ers,25,12,2018,1.49,2.70,121,114,1,1,Boston Celtics - Philadelphia 76ers,121:114 ET,1,0.644391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2294,Toronto Raptors,Miami Heat,7,4,2019,1.42,2.96,117,109,1,1,Toronto Raptors - Miami Heat,117:109 ET,1,0.675799
2397,Washington Wizards,Houston Rockets,27,11,2018,1.81,2.04,135,131,1,1,Washington Wizards - Houston Rockets,135:131 ET,1,0.529870
2405,Washington Wizards,Boston Celtics,13,12,2018,2.44,1.58,125,130,1,1,Washington Wizards - Boston Celtics,125:130 ET,0,0.393035
2410,Washington Wizards,Phoenix Suns,23,12,2018,1.50,2.67,149,146,1,1,Washington Wizards - Phoenix Suns,149:146 ET,1,0.640288
2421,Washington Wizards,Toronto Raptors,13,1,2019,2.73,1.47,138,140,1,1,Washington Wizards - Toronto Raptors,138:140 ET,0,0.350000

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the game went to overtime?
np.corrcoef(NBA19_Overtime["winprob"], NBA19_Overtime['win'])

array([[1.        , 0.03225853],
       [0.03225853, 1.        ]])

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the game was finished in regular time?
np.corrcoef(NBA19_Regulation["winprob"], NBA19_Regulation['win'])

array([[1.       , 0.4144347],
       [0.4144347, 1.       ]])

From these correlations we can assume that uncertain games are the ones where the bookmakers odds are most likely to be wrong and these games are the ones that tend to go into overtime. Overtime games are usually closer, so a big spread that goes into overtime might not even be possible to cover a game once it has gone into overtime making it harder to predict the outcome initially without knowing the game will go into overtime.

In [ ]:
#c
NBA19_2018= NBA19[NBA19['year'] == 2018]
NBA19_2019 =  NBA19[NBA19['year'] == 2019]
NBA19_2018

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
7,Atlanta Hawks,Sacramento Kings,2,11,2018,2.16,1.73,115,146,0,1,Atlanta Hawks - Sacramento Kings,115:146,0,0.444730
8,Atlanta Hawks,Miami Heat,4,11,2018,2.91,1.43,123,118,0,1,Atlanta Hawks - Miami Heat,123:118,1,0.329493
10,Atlanta Hawks,New York Knicks,8,11,2018,2.00,1.83,107,112,0,1,Atlanta Hawks - New York Knicks,107:112,0,0.477807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,Washington Wizards,Boston Celtics,13,12,2018,2.44,1.58,125,130,1,1,Washington Wizards - Boston Celtics,125:130 ET,0,0.393035
2407,Washington Wizards,Los Angeles Lakers,17,12,2018,2.36,1.61,128,110,0,1,Washington Wizards - Los Angeles Lakers,128:110,1,0.405542
2410,Washington Wizards,Phoenix Suns,23,12,2018,1.50,2.67,149,146,1,1,Washington Wizards - Phoenix Suns,149:146 ET,1,0.640288
2413,Washington Wizards,Chicago Bulls,29,12,2018,1.52,2.60,92,101,0,1,Washington Wizards - Chicago Bulls,92:101,0,0.631068
2414,Washington Wizards,Charlotte Hornets,30,12,2018,2.37,1.62,130,126,0,1,Washington Wizards - Charlotte Hornets,130:126,1,0.406015

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2018?
np.corrcoef(NBA19_2018["winprob"], NBA19_2018['win'])

array([[1.        , 0.33824657],
       [0.33824657, 1.        ]])

In [ ]:
# What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2019?
np.corrcoef(NBA19_2019["winprob"], NBA19_2019['win'])

array([[1.        , 0.43797601],
       [0.43797601, 1.        ]])

From these correlations we can assume that uncertain games are the ones where the bookmakers odds are most likely to be wrong and these games are the ones in the 2018 year.  One reason for this could be uncertainty of how a team could perform with new additions and therefore setting tentative lines.  But once the season has gotten a good bit underway it will be easier to set better lines.

In [ ]:
#d
NBA19_Oct = NBA19[NBA19['month'] == 10]
NBA19_Nov =  NBA19[NBA19['month'] == 11]
NBA19_Dec =  NBA19[NBA19['month'] == 12]
NBA19_Jan =  NBA19[NBA19['month'] == 1]
NBA19_Feb =  NBA19[NBA19['month'] == 2]
NBA19_March =  NBA19[NBA19['month'] == 3]
NBA19_April =  NBA19[NBA19['month'] == 4]
NBA19_Oct

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
82,Boston Celtics,Philadelphia 76ers,17,10,2018,1.46,2.76,105,87,0,1,Boston Celtics - Philadelphia 76ers,105:87,1,0.654028
85,Boston Celtics,Orlando Magic,23,10,2018,1.11,7.06,90,93,0,1,Boston Celtics - Orlando Magic,90:93,0,0.864137
88,Boston Celtics,Detroit Pistons,31,10,2018,1.24,4.27,108,105,0,1,Boston Celtics - Detroit Pistons,108:105,1,0.774955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221,Toronto Raptors,Philadelphia 76ers,31,10,2018,1.39,3.08,129,112,0,1,Toronto Raptors - Philadelphia 76ers,129:112,1,0.689038
2297,Utah Jazz,Golden State Warriors,20,10,2018,2.17,1.72,123,124,0,1,Utah Jazz - Golden State Warriors,123:124,0,0.442159
2298,Utah Jazz,Memphis Grizzlies,23,10,2018,1.17,5.47,84,92,0,1,Utah Jazz - Memphis Grizzlies,84:92,0,0.823795
2378,Washington Wizards,Miami Heat,19,10,2018,1.40,3.03,112,113,0,1,Washington Wizards - Miami Heat,112:113,0,0.683973
2379,Washington Wizards,Toronto Raptors,21,10,2018,1.78,2.07,113,117,0,1,Washington Wizards - Toronto Raptors,113:117,0,0.537662

In [ ]:
# In which month was the correlation coefficient between the home team win probability and home team wins greatest? The Least?
np.corrcoef(NBA19_Oct["winprob"], NBA19_Oct['win'])

array([[1.       , 0.4132173],
       [0.4132173, 1.       ]])

In [ ]:
np.corrcoef(NBA19_Nov["winprob"], NBA19_Nov['win'])

array([[1.        , 0.31889017],
       [0.31889017, 1.        ]])

In [ ]:
np.corrcoef(NBA19_Dec["winprob"], NBA19_Dec['win'])

array([[1.        , 0.32183843],
       [0.32183843, 1.        ]])

In [ ]:
np.corrcoef(NBA19_Jan["winprob"], NBA19_Jan['win'])

array([[1.       , 0.5035297],
       [0.5035297, 1.       ]])

In [ ]:
np.corrcoef(NBA19_Feb["winprob"], NBA19_Feb['win'])

array([[1.        , 0.37928007],
       [0.37928007, 1.        ]])

In [ ]:
np.corrcoef(NBA19_March["winprob"], NBA19_March['win'])

array([[1.        , 0.41270836],
       [0.41270836, 1.        ]])

In [ ]:
np.corrcoef(NBA19_April["winprob"], NBA19_April['win'])

array([[1.       , 0.4554355],
       [0.4554355, 1.       ]])

### Conclusion:

As stated above, by doing this analysis, it allows is to discover how certain factors are what makes any sports only forecastable to a certain degree. Random underlying factors that could just pop up on any given night can prove difficult to impossible to predict which could lead to even the best bookmakers setting bad lines.