In [79]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [80]:
#Load packages
import pandas as pd
import numpy as np

# I. Coding Run Expectancy Dataset (2017)

In [81]:
# Read in MLBAM Data for 2017

MLBAM17 = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 4 Content/Week 4 Assignment/MLBAM17.csv")

In [82]:
# Drop column with no relevant information and set max columns to display to 100
MLBAM17.drop(['Unnamed: 0'], axis=1, inplace=True)

pd.set_option('display.max_columns', 100)
MLBAM17

,inning,batterId,pitcherId,event,x,y,ab_num,timestamp,stand,throws,runnerMovement,half,balls,strikes,endOuts,actionId,description,game_type,home_team,home_teamId,home_lg,away_team,away_teamId,away_lg,venueId,stadium,field_teamId,playerId.1B,playerId.2B,playerId.3B,playerId.C,playerId.CF,playerId.LF,playerId.RF,playerId.SS,batterPos,batterName,pitcherName,runsOnPlay,startOuts,runsInInning,runsITD,runsFuture,start1B,start2B,start3B,end1B,end2B,end3B,outsInInning,startCode,endCode,fielderId,gameId,isPA,isAB,isHit,isBIP,our.x,our.y,r,theta
0,1,458731,502042,Flyout,65.59,123.50,1,2017-04-02 17:12:18,L,R,NaN,top,2,2,1,NaN,Brett Gardner flies out to left fielder Mallex...,R,tba,139,AL,nya,147,AL,12,Tropicana Field,139,489149,543543,446334,519083,595281,605480,519306,542921,LF,Gardner,Archer,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-148.267814,188.423160,239.763700,2.237490
1,1,596142,502042,Groundout,128.19,193.88,2,2017-04-02 17:15:42,R,R,NaN,top,0,0,2,NaN,"Gary Sanchez grounds out sharply, pitcher Chri...",R,tba,139,AL,nya,147,AL,12,Tropicana Field,139,489149,543543,446334,519083,595281,605480,519306,542921,C,"Sanchez, G",Archer,0,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,502042.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,7.961190,12.777835,15.055020,1.013603
2,1,595885,502042,Walk,NaN,NaN,3,2017-04-02 17:16:48,L,R,[595885::1B::Walk],top,4,1,2,NaN,Greg Bird walks.,R,tba,139,AL,nya,147,AL,12,Tropicana Field,139,489149,543543,446334,519083,595281,605480,519306,542921,1B,Bird,Archer,0,2,0,0,0,NaN,NaN,NaN,595885.0,NaN,NaN,3,0,1,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
3,1,407812,502042,Groundout,153.48,157.29,4,2017-04-02 17:19:09,R,R,[595885:1B:::Groundout],top,3,1,3,NaN,"Yankees challenged (play at 1st), call on the ...",R,tba,139,AL,nya,147,AL,12,Tropicana Field,139,489149,543543,446334,519083,595281,605480,519306,542921,DH,Holliday,Archer,0,2,0,0,0,595885.0,NaN,NaN,NaN,NaN,NaN,3,1,0,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,71.076710,104.094437,126.045827,0.971701
4,1,572816,547888,Single,140.75,73.31,5,2017-04-02 17:24:43,L,R,[572816::1B::Single],bottom,0,1,0,NaN,Corey Dickerson singles on a sharp line drive ...,R,tba,139,AL,nya,147,AL,12,Tropicana Field,147,595885,516770,452104,596142,453056,458731,592450,591720,DH,"Dickerson, C",Tanaka,0,0,3,0,3,NaN,NaN,NaN,572816.0,NaN,NaN,3,0,1,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,39.306818,313.680887,316.134030,1.446138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,9,572227,596027,Runner Out,NaN,NaN,65,2017-10-01 21:44:19,R,R,[571740:1B:::Caught Stealing 3B][608385:2B:::C...,top,0,1,3,NaN,"Reds challenged (tag play), call on the field ...",R,chn,112,NL,cin,113,NL,17,Wrigley Field,112,519203,595879,592178,488671,445055,450314,518792,608365,UN,Vincej,Maples,0,2,0,0,0,571740.0,608385.0,NaN,NaN,NaN,NaN,3,3,0,NaN,gid_2017_10_01_cinmlb_chnmlb_1,False,False,False,False,NaN,NaN,NaN,NaN
185591,9,543089,628452,Groundout,142.89,147.02,66,2017-10-01 21:49:41,R,R,NaN,bottom,0,0,1,NaN,"Taylor Davis grounds out, second baseman Scoot...",R,chn,112,NL,cin,113,NL,17,Wrigley Field,113,458015,571697,553993,571466,571740,594807,640447,446359,UN,"Davis, T","Iglesias, R",0,0,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,44.647554,129.724978,137.193200,1.239324
185592,9,546991,628452,Home Run,119.91,21.25,67,2017-10-01 21:50:11,R,R,[546991:::T:Home Run],bottom,1,0,1,NaN,Albert Almora homers (8) on a fly ball to cent...,R,chn,112,NL,cin,113,NL,17,Wrigley Field,113,458015,571697,553993,571466,571740,594807,640447,446359,UN,Almora Jr.,"Iglesias, R",1,1,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,False,-12.702965,443.605519,443.787361,1.599424
185593,9,502273,628452,Groundout,127.01,201.44,68,2017-10-01 21:51:15,L,R,NaN,bottom,0,0,2,NaN,"Mike Freeman grounds out, second baseman Scoot...",R,chn,112,NL,cin,113,NL,17,Wrigley Field,113,458015,571697,553993,571466,571740,594807,640447,446359,UN,Freeman,"Iglesias, R",0,1,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,5.016299,-6.089437,7.889518,-0.881728
185594,9,450314,628452,Groundout,126.83,200.86,69,2017-10-01 21:51:48,L,R,NaN,bottom,0,0,3,NaN,"Ben Zobrist grounds out, second baseman Scoote...",R,chn,112,NL,cin,113,NL,17,Wrigley Field,113,458015,571697,553993,571466,571740,594807,640447,446359,LF,Zobrist,"Iglesias, R",0,2,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,4.567078,-4.641948,6.511980,-0.793528

In [83]:
# Keep only relevant columns to our data analysis
RE17 = MLBAM17[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                   'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                   'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF

In [84]:
# Create three indicator variables (one for each base) to denote whether or not each base is occupied prior to the plate appearance.
RE17['Start1'] = np.where(pd.isnull(RE17['start1B']),0,1)
RE17['Start2'] = np.where(pd.isnull(RE17['start2B']),0,1)
RE17['Start3'] = np.where(pd.isnull(RE17['start3B']),0,1)
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0

In [85]:
# Create a “start state” variable to denote the base out state prior to each plate appearance
RE17['Start_State'] = (RE17['Start1'].astype(str) + RE17['Start2'].astype(str) + RE17['Start3'].astype(str)+\
                          " " + RE17['startOuts'].astype(str))
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2

In [86]:
# Create three indicator variables (one for each base) to denote whether or not each base is occupied after the plate appearance.
RE17['End1'] = np.where(pd.isnull(RE17['end1B']),0,1)
RE17['End2'] = np.where(pd.isnull(RE17['end2B']),0,1)
RE17['End3'] = np.where(pd.isnull(RE17['end3B']),0,1)
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0

In [87]:
# Create an “end state” variable to denote the base out state after each plate appearance.
RE17['End_State'] = (RE17['End1'].astype(str) + RE17['End2'].astype(str) + RE17['End3'].astype(str) + \
                        " " + RE17['endOuts'].astype(str))
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [88]:
# Restrict data to plays where either there is a change in state/runs scored and innings in which there were exactly 3 outs recorded
RE17 = RE17[((RE17.Start_State != RE17.End_State) | (RE17.runsOnPlay > 0)) & (RE17.outsInInning == 3)]
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [89]:
# Calculate run expectancy by starting state and merge this into play by play data.
Start_RunExp = RE17.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})
display(Start_RunExp)

   Start_State  Start_RE
0        000 0  0.516375
1        000 1  0.272176
2        000 2  0.108038
3        001 0  1.436482
4        001 1  0.953586
5        001 2  0.381186
6        010 0  1.154829
7        010 1  0.711650
8        010 2  0.336702
9        011 0  2.051376
10       011 1  1.517131
11       011 2  0.601763
12       100 0  0.912921
13       100 1  0.524904
14       100 2  0.225365
15       101 0  1.838889
16       101 1  1.215306
17       101 2  0.496480
18       110 0  1.509497
19       110 1  0.947424
20       110 2  0.449782
21       111 0  2.241581
22       111 1  1.635608
23       111 2  0.804609

In [90]:
RE17 = pd.merge(RE17, Start_RunExp, on=['Start_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1,0.516375
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2,0.272176
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2,0.108038
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3,0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0,0.516375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3,0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3,0.108038

In [91]:
# Using the run expectancy data by starting state, create a variable to denote run expectancy by ending state
#(in addition, make sure to include the base out states for which there are 3 outs with run expectancies of 0 to the run expectancy by ending state data)
Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]
Base_State_3

[Start_State    000 3
 Start_RE           0
 dtype: object,
 Start_State    001 3
 Start_RE           0
 dtype: object,
 Start_State    010 3
 Start_RE           0
 dtype: object,
 Start_State    011 3
 Start_RE           0
 dtype: object,
 Start_State    100 3
 Start_RE           0
 dtype: object,
 Start_State    101 3
 Start_RE           0
 dtype: object,
 Start_State    110 3
 Start_RE           0
 dtype: object,
 Start_State    111 3
 Start_RE           0
 dtype: object]

In [92]:
Start_RunExp = pd.concat([Start_RunExp, pd.DataFrame(Base_State_3)], ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

display(End_RunExp)

   End_State    End_RE
0      000 0  0.516375
1      000 1  0.272176
2      000 2  0.108038
3      001 0  1.436482
4      001 1  0.953586
5      001 2  0.381186
6      010 0  1.154829
7      010 1  0.711650
8      010 2  0.336702
9      011 0  2.051376
10     011 1  1.517131
11     011 2  0.601763
12     100 0  0.912921
13     100 1  0.524904
14     100 2  0.225365
15     101 0  1.838889
16     101 1  1.215306
17     101 2  0.496480
18     110 0  1.509497
19     110 1  0.947424
20     110 2  0.449782
21     111 0  2.241581
22     111 1  1.635608
23     111 2  0.804609
24     000 3  0.000000
25     001 3  0.000000
26     010 3  0.000000
27     011 3  0.000000
28     100 3  0.000000
29     101 3  0.000000
30     110 3  0.000000
31     111 3  0.000000

In [93]:
# Merge the ending state run expectancy into the play by play data.
RE17 = pd.merge(RE17, End_RunExp, on=['End_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3,0.225365,0.000000
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0,0.516375,0.912921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000

In [94]:
# Calculate the run value of each event
RE17['Run_Value'] = RE17['runsOnPlay'] + RE17['End_RE'] - RE17['Start_RE']

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3,0.225365,0.000000,-0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0,0.516375,0.912921,0.396546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038

# II. Coding Run Expectancy Dataset (2016)

In [95]:
# Read in MLBAM Data for 2016

MLBAM16 = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 4 Content/Week 4 Assignment/MLBAM16.csv")

In [96]:
# Drop column with no relevant information and set max columns to display to 100
MLBAM16.drop(['Unnamed: 0'], axis=1, inplace=True)

pd.set_option('display.max_columns', 100)
MLBAM16

,inning,batterId,pitcherId,event,x,y,ab_num,timestamp,stand,throws,runnerMovement,half,balls,strikes,endOuts,actionId,description,game_type,home_team,home_teamId,home_lg,away_team,away_teamId,away_lg,venueId,stadium,field_teamId,playerId.1B,playerId.2B,playerId.3B,playerId.C,playerId.CF,playerId.LF,playerId.RF,playerId.SS,batterPos,batterName,pitcherName,runsOnPlay,startOuts,runsInInning,runsITD,runsFuture,start1B,start2B,start3B,end1B,end2B,end3B,outsInInning,startCode,endCode,fielderId,gameId,isPA,isAB,isHit,isBIP,our.x,our.y,r,theta
0,1,572761,434538,Groundout,156.52,164.65,1,2016-04-03 17:15:13,L,L,NaN,top,1,0,1,NaN,"Matt Carpenter grounds out, first baseman John...",R,pit,134,NL,sln,138,NL,31,PNC Park,134,444379,543281,501896,465041,457705,516782,570256,474568,3B,"Carpenter, M",Liriano,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,444379.0,gid_2016_04_03_slnmlb_pitmlb_1,True,True,False,True,78.663550,85.726299,116.348409,0.828335
1,1,502054,434538,Groundout,115.36,180.41,2,2016-04-03 17:16:36,R,L,NaN,top,0,0,2,NaN,"Tommy Pham grounds out softly, third baseman D...",R,pit,134,NL,sln,138,NL,31,PNC Park,134,444379,543281,501896,465041,457705,516782,570256,474568,LF,Pham,Liriano,0,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,501896.0,gid_2016_04_03_slnmlb_pitmlb_1,True,True,False,True,-24.058268,46.394524,52.261383,2.049180
2,1,407812,434538,Strikeout,NaN,NaN,3,2016-04-03 17:17:18,R,L,NaN,top,3,3,3,NaN,Matt Holliday called out on strikes.,R,pit,134,NL,sln,138,NL,31,PNC Park,134,444379,543281,501896,465041,457705,516782,570256,474568,1B,Holliday,Liriano,0,2,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,NaN,gid_2016_04_03_slnmlb_pitmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
3,1,444379,425794,Groundout,150.43,162.62,4,2016-04-03 17:21:26,L,R,NaN,bottom,0,1,1,NaN,"John Jaso grounds out, second baseman Kolten W...",R,pit,134,NL,sln,138,NL,31,PNC Park,138,407812,543939,572761,425877,545341,502054,572039,576397,1B,Jaso,Wainwright,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,543939.0,gid_2016_04_03_slnmlb_pitmlb_1,True,True,False,True,63.464913,90.792511,110.774885,0.960735
4,1,457705,425794,Hit By Pitch,NaN,NaN,5,2016-04-03 17:22:29,R,R,[457705::1B::Hit By Pitch],bottom,1,2,1,NaN,"Cardinals challenged (hit by pitch), call on t...",R,pit,134,NL,sln,138,NL,31,PNC Park,138,407812,543939,572761,425877,545341,502054,572039,576397,CF,McCutchen,Wainwright,0,1,0,0,0,NaN,NaN,NaN,457705.0,NaN,NaN,3,0,1,NaN,gid_2016_04_03_slnmlb_pitmlb_1,True,False,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,8,461235,592866,Strikeout,NaN,NaN,77,2016-10-02 22:17:42,L,R,[594824:1B:::Strikeout],bottom,0,3,3,NaN,Brandon Moss strikes out swinging.,R,sln,138,NL,pit,134,NL,2889,Busch Stadium,134,444379,593700,628356,518700,457705,459964,570256,465753,LF,Moss,"Williams, T",0,2,0,0,0,594824.0,NaN,NaN,NaN,NaN,NaN,3,1,0,NaN,gid_2016_10_02_pitmlb_slnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
184931,9,595386,518883,Groundout,114.21,159.04,78,2016-10-02 22:22:07,R,L,NaN,top,1,2,1,NaN,"Jason Rogers grounds out, shortstop Aledmys Di...",R,sln,138,NL,pit,134,NL,2889,Busch Stadium,138,572761,576397,425509,425877,545341,461235,572039,649557,UN,"Rogers, J",Kiekhefer,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,649557.0,gid_2016_10_02_pitmlb_slnmlb_1,True,True,False,True,-26.928290,99.727013,103.298644,1.834527
184932,9,444379,518883,Walk,NaN,NaN,79,2016-10-02 22:24:44,L,L,[444379::1B::Walk],top,4,2,1,NaN,John Jaso walks.,R,sln,138,NL,pit,134,NL,2889,Busch Stadium,138,572761,576397,425509,425877,545341,461235,572039,649557,1B,Jaso,Kiekhefer,0,1,0,0,0,NaN,NaN,NaN,444379.0,NaN,NaN,3,0,1,NaN,gid_2016_10_02_pitmlb_slnmlb_1,True,False,False,False,NaN,NaN,NaN,NaN
184933,9,570256,518883,Strikeout,NaN,NaN,80,2016-10-02 22:26:38,L,L,NaN,top,1,3,2,NaN,Gregory Polanco called out on strikes.,R,sln,138,NL,pit,134,NL,2889,Busch Stadium,138,572761,576397,425509,425877,545341,461235,572039,649557,RF,"Polanco, G",Kiekhefer,0,1,0,0,0,444379.0,NaN,NaN,444379.0,NaN,NaN,3,1,1,NaN,gid_2016_10_02_pitmlb_slnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
184934,9,457705,518883,Groundout,128.42,184.98,81,2016-10-02 22:28:12,R,L,[444379:1B:::Groundout],top,1,0,3,NaN,"Andrew McCutchen grounds out, pitcher Dean Kie...",R,sln,138,NL,pit,134,NL,2889,Busch Stadium,138,572761,576397,425509,425877,545341,461235,572039,649557,CF,McCutchen,Kiekhefer,0,2,0,0,0,444379.0,NaN,NaN,NaN,NaN,NaN,3,1,0,518883.0,gid_2016_10_02_pitmlb_slnmlb_1,True,True,False,True,8.535195,34.989307,36.015291,1.331532

In [97]:
# Keep only relevant columns to our data analysis
RE16 = MLBAM16[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                   'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                   'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF

In [98]:
# Create three indicator variables (one for each base) to denote whether or not each base is occupied prior to the plate appearance.
RE16['Start1'] = np.where(pd.isnull(RE16['start1B']),0,1)
RE16['Start2'] = np.where(pd.isnull(RE16['start2B']),0,1)
RE16['Start3'] = np.where(pd.isnull(RE16['start3B']),0,1)
RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0

In [99]:
# Create a “start state” variable to denote the base out state prior to each plate appearance
RE16['Start_State'] = (RE16['Start1'].astype(str) + RE16['Start2'].astype(str) + RE16['Start3'].astype(str)+\
                          " " + RE16['startOuts'].astype(str))
RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2

In [100]:
# Create three indicator variables (one for each base) to denote whether or not each base is occupied after the plate appearance.
RE16['End1'] = np.where(pd.isnull(RE16['end1B']),0,1)
RE16['End2'] = np.where(pd.isnull(RE16['end2B']),0,1)
RE16['End3'] = np.where(pd.isnull(RE16['end3B']),0,1)
RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0

In [101]:
# Create an “end state” variable to denote the base out state after each plate appearance.
RE16['End_State'] = (RE16['End1'].astype(str) + RE16['End2'].astype(str) + RE16['End3'].astype(str) + \
                        " " + RE16['endOuts'].astype(str))
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0,000 1
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0,000 2
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0,000 3
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0,000 1
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0,100 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3

In [102]:
# Restrict data to plays where either there is a change in state/runs scored and innings in which there were exactly 3 outs recorded
RE16 = RE16[((RE16.Start_State != RE16.End_State) | (RE16.runsOnPlay > 0)) & (RE16.outsInInning == 3)]
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0,000 1
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0,000 2
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0,000 3
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0,000 1
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0,100 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3

In [103]:
# Calculate run expectancy by starting state and merge this into play by play data.
Start_RunExp = RE16.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})
display(Start_RunExp)

   Start_State  Start_RE
0        000 0  0.498377
1        000 1  0.268678
2        000 2  0.106305
3        001 0  1.358166
4        001 1  0.948684
5        001 2  0.377197
6        010 0  1.132468
7        010 1  0.677498
8        010 2  0.319844
9        011 0  1.916190
10       011 1  1.343899
11       011 2  0.587466
12       100 0  0.858504
13       100 1  0.512225
14       100 2  0.220539
15       101 0  1.728145
16       101 1  1.196777
17       101 2  0.480175
18       110 0  1.447597
19       110 1  0.922572
20       110 2  0.414466
21       111 0  2.112409
22       111 1  1.536937
23       111 2  0.696658

In [104]:
RE16 = pd.merge(RE16, Start_RunExp, on=['Start_State'], how='left')
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0,000 1,0.498377
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0,000 2,0.268678
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0,000 3,0.106305
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0,000 1,0.498377
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0,100 1,0.268678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3,0.220539
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1,0.498377
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1,0.268678
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2,0.512225
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3,0.220539

In [105]:
# Using the run expectancy data by starting state, create a variable to denote run expectancy by ending state
#(in addition, make sure to include the base out states for which there are 3 outs with run expectancies of 0 to the run expectancy by ending state data)
Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]
Base_State_3

[Start_State    000 3
 Start_RE           0
 dtype: object,
 Start_State    001 3
 Start_RE           0
 dtype: object,
 Start_State    010 3
 Start_RE           0
 dtype: object,
 Start_State    011 3
 Start_RE           0
 dtype: object,
 Start_State    100 3
 Start_RE           0
 dtype: object,
 Start_State    101 3
 Start_RE           0
 dtype: object,
 Start_State    110 3
 Start_RE           0
 dtype: object,
 Start_State    111 3
 Start_RE           0
 dtype: object]

In [106]:
Start_RunExp = pd.concat([Start_RunExp, pd.DataFrame(Base_State_3)], ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

display(End_RunExp)

   End_State    End_RE
0      000 0  0.498377
1      000 1  0.268678
2      000 2  0.106305
3      001 0  1.358166
4      001 1  0.948684
5      001 2  0.377197
6      010 0  1.132468
7      010 1  0.677498
8      010 2  0.319844
9      011 0  1.916190
10     011 1  1.343899
11     011 2  0.587466
12     100 0  0.858504
13     100 1  0.512225
14     100 2  0.220539
15     101 0  1.728145
16     101 1  1.196777
17     101 2  0.480175
18     110 0  1.447597
19     110 1  0.922572
20     110 2  0.414466
21     111 0  2.112409
22     111 1  1.536937
23     111 2  0.696658
24     000 3  0.000000
25     001 3  0.000000
26     010 3  0.000000
27     011 3  0.000000
28     100 3  0.000000
29     101 3  0.000000
30     110 3  0.000000
31     111 3  0.000000

In [107]:
# Merge the ending state run expectancy into the play by play data.
RE16 = pd.merge(RE16, End_RunExp, on=['End_State'], how='left')
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2,0.512225,0.220539
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000

In [108]:
# Calculate the run value of each event
RE16['Run_Value'] = RE16['runsOnPlay'] + RE16['End_RE'] - RE16['Start_RE']

display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539

# III. Comparing 2016 vs. 2017

In [117]:
# Calculate the average run value for each event for both 2016 and 2017.
Event_Value_17 = RE17.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value_17 = Event_Value_17.rename(columns={'Run_Value':'Run_Value_17'})
Event_Value_17

                   event  Run_Value_17
0    Batter Interference     -0.430019
1         Bunt Groundout     -0.209411
2           Bunt Lineout     -0.328292
3           Bunt Pop Out     -0.373225
4   Catcher Interference      0.399070
5                 Double      0.779338
6            Double Play     -0.897164
7       Fan interference      0.590743
8            Field Error      0.493206
9        Fielders Choice      0.764112
10   Fielders Choice Out     -0.662400
11                Flyout     -0.262548
12              Forceout     -0.345347
13      Grounded Into DP     -0.818005
14             Groundout     -0.224579
15          Hit By Pitch      0.338679
16              Home Run      1.378739
17           Intent Walk      0.180109
18               Lineout     -0.259682
19               Pop Out     -0.283498
20            Runner Out     -0.274991
21              Sac Bunt     -0.109283
22               Sac Fly     -0.032119
23            Sac Fly DP     -0.543715
24                Single      0.455773
25             Strikeout     -0.269985
26        Strikeout - DP     -0.682819
27                Triple      1.063607
28           Triple Play     -1.471223
29                  Walk      0.322635

In [118]:
Event_Value_16 = RE16.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value_16 = Event_Value_16.rename(columns={'Run_Value':'Run_Value_16'})
Event_Value_16

                   event  Run_Value_16
0    Batter Interference     -0.284649
1         Bunt Groundout     -0.218826
2           Bunt Lineout     -0.352295
3           Bunt Pop Out     -0.342802
4   Catcher Interference      0.301623
5                 Double      0.743467
6            Double Play     -0.864981
7       Fan interference      0.533316
8            Field Error      0.469989
9        Fielders Choice      0.701447
10   Fielders Choice Out     -0.610757
11                Flyout     -0.247896
12              Forceout     -0.326657
13      Grounded Into DP     -0.773318
14             Groundout     -0.212992
15          Hit By Pitch      0.320569
16              Home Run      1.382476
17           Intent Walk      0.172551
18               Lineout     -0.248542
19               Pop Out     -0.267062
20            Runner Out     -0.257904
21              Sac Bunt     -0.126691
22               Sac Fly      0.023233
23            Sac Fly DP     -0.370443
24     Sacrifice Bunt DP     -0.752199
25                Single      0.440258
26             Strikeout     -0.259940
27        Strikeout - DP     -0.622787
28                Triple      1.023911
29           Triple Play     -1.637543
30                  Walk      0.299404

In [119]:
# Merge the 2016 and 2017 run values by event into one dataframe
Event_Value = pd.merge(Event_Value_16, Event_Value_17, on=['event'], how='left')
Event_Value

                   event  Run_Value_16  Run_Value_17
0    Batter Interference     -0.284649     -0.430019
1         Bunt Groundout     -0.218826     -0.209411
2           Bunt Lineout     -0.352295     -0.328292
3           Bunt Pop Out     -0.342802     -0.373225
4   Catcher Interference      0.301623      0.399070
5                 Double      0.743467      0.779338
6            Double Play     -0.864981     -0.897164
7       Fan interference      0.533316      0.590743
8            Field Error      0.469989      0.493206
9        Fielders Choice      0.701447      0.764112
10   Fielders Choice Out     -0.610757     -0.662400
11                Flyout     -0.247896     -0.262548
12              Forceout     -0.326657     -0.345347
13      Grounded Into DP     -0.773318     -0.818005
14             Groundout     -0.212992     -0.224579
15          Hit By Pitch      0.320569      0.338679
16              Home Run      1.382476      1.378739
17           Intent Walk      0.172551      0.180109
18               Lineout     -0.248542     -0.259682
19               Pop Out     -0.267062     -0.283498
20            Runner Out     -0.257904     -0.274991
21              Sac Bunt     -0.126691     -0.109283
22               Sac Fly      0.023233     -0.032119
23            Sac Fly DP     -0.370443     -0.543715
24     Sacrifice Bunt DP     -0.752199           NaN
25                Single      0.440258      0.455773
26             Strikeout     -0.259940     -0.269985
27        Strikeout - DP     -0.622787     -0.682819
28                Triple      1.023911      1.063607
29           Triple Play     -1.637543     -1.471223
30                  Walk      0.299404      0.322635

In [120]:
# Calculate the aggregate run value (sum) for all players in both 2016 and 2017
Player_Value_17 = RE17.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value_17 = Player_Value_17.rename(columns={'Run_Value':'Run_Value_17'})
Player_Value_17

      batterName  Run_Value_17
0          Abreu     31.392604
1         Adames     -2.872021
2          Adams      9.681144
3       Adams, L      5.448181
4       Adams, M     -0.496480
..           ...           ...
957       Zunino      4.710472
958     d'Arnaud     -7.884709
959  d'Arnaud, T     -2.301919
960       deGrom     -9.500759
961   den Dekker     -1.647911

[962 rows x 2 columns]

In [121]:
Player_Value_16 = RE16.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value_16 = Player_Value_16.rename(columns={'Run_Value':'Run_Value_16'})
Player_Value_16

      batterName  Run_Value_16
0           Abad     -0.162373
1          Abreu     13.395343
2         Ackley     -4.006312
3         Adames    -12.866394
4          Adams      4.063644
..           ...           ...
959       Zunino      8.816774
960     d'Arnaud    -10.768827
961  d'Arnaud, T    -12.314196
962       deGrom     -8.532559
963   den Dekker      0.085717

[964 rows x 2 columns]

In [123]:
# Merge the 2016 and 2017 run values by player into one dataframe so that only players appearing in both datasets appear in the merged data
Player_Value = pd.merge(Player_Value_16, Player_Value_17, on=['batterName'], how='inner')
Player_Value

      batterName  Run_Value_16  Run_Value_17
0          Abreu     13.395343     31.392604
1         Adames    -12.866394     -2.872021
2          Adams      4.063644      9.681144
3        Adleman      0.713572     -5.242051
4       Adrianza     -3.300578      0.425352
..           ...           ...           ...
686       Zunino      8.816774      4.710472
687     d'Arnaud    -10.768827     -7.884709
688  d'Arnaud, T    -12.314196     -2.301919
689       deGrom     -8.532559     -9.500759
690   den Dekker      0.085717     -1.647911

[691 rows x 3 columns]

In [131]:
Player_Value['diff'] = Player_Value['Run_Value_17']-Player_Value['Run_Value_16']
Player_Value

      batterName  Run_Value_16  Run_Value_17       diff
0          Abreu     13.395343     31.392604  17.997261
1         Adames    -12.866394     -2.872021   9.994373
2          Adams      4.063644      9.681144   5.617500
3        Adleman      0.713572     -5.242051  -5.955624
4       Adrianza     -3.300578      0.425352   3.725930
..           ...           ...           ...        ...
686       Zunino      8.816774      4.710472  -4.106302
687     d'Arnaud    -10.768827     -7.884709   2.884118
688  d'Arnaud, T    -12.314196     -2.301919  10.012276
689       deGrom     -8.532559     -9.500759  -0.968200
690   den Dekker      0.085717     -1.647911  -1.733628

[691 rows x 4 columns]

In [130]:
Event_Value['diff'] = Event_Value['Run_Value_17']-Event_Value['Run_Value_16']
Event_Value

                   event  Run_Value_16  Run_Value_17      diff
0    Batter Interference     -0.284649     -0.430019 -0.145369
1         Bunt Groundout     -0.218826     -0.209411  0.009415
2           Bunt Lineout     -0.352295     -0.328292  0.024003
3           Bunt Pop Out     -0.342802     -0.373225 -0.030423
4   Catcher Interference      0.301623      0.399070  0.097447
5                 Double      0.743467      0.779338  0.035870
6            Double Play     -0.864981     -0.897164 -0.032183
7       Fan interference      0.533316      0.590743  0.057427
8            Field Error      0.469989      0.493206  0.023217
9        Fielders Choice      0.701447      0.764112  0.062665
10   Fielders Choice Out     -0.610757     -0.662400 -0.051643
11                Flyout     -0.247896     -0.262548 -0.014652
12              Forceout     -0.326657     -0.345347 -0.018691
13      Grounded Into DP     -0.773318     -0.818005 -0.044687
14             Groundout     -0.212992     -0.224579 -0.011588
15          Hit By Pitch      0.320569      0.338679  0.018110
16              Home Run      1.382476      1.378739 -0.003737
17           Intent Walk      0.172551      0.180109  0.007558
18               Lineout     -0.248542     -0.259682 -0.011140
19               Pop Out     -0.267062     -0.283498 -0.016436
20            Runner Out     -0.257904     -0.274991 -0.017087
21              Sac Bunt     -0.126691     -0.109283  0.017409
22               Sac Fly      0.023233     -0.032119 -0.055352
23            Sac Fly DP     -0.370443     -0.543715 -0.173272
24     Sacrifice Bunt DP     -0.752199           NaN       NaN
25                Single      0.440258      0.455773  0.015515
26             Strikeout     -0.259940     -0.269985 -0.010045
27        Strikeout - DP     -0.622787     -0.682819 -0.060032
28                Triple      1.023911      1.063607  0.039695
29           Triple Play     -1.637543     -1.471223  0.166319
30                  Walk      0.299404      0.322635  0.023231