In [1]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [157]:
# First we load the packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# I. Building the Dataset: Player Stats

In [158]:
# Read in salary data retrieved from Lahman's Database
Salary = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 2 Content/Week 2 Assignment/Salaries.csv")

# Read in batting
Batting = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 2 Content/Week 2 Assignment/Batting.csv")
pd.set_option('display.max_columns', 50)

In [159]:
# Not every salary is recorded, so first drop missing values
Salary = Salary[Salary.salary > 0]
Salary

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26426 rows x 5 columns]

In [160]:
# Calculate natural log of salary
Salary['lnSal'] = np.log(Salary['salary'])
Salary

       yearID teamID lgID   playerID    salary      lnSal
0        1985    ATL   NL  barkele01    870000  13.676248
1        1985    ATL   NL  bedrost01    550000  13.217674
2        1985    ATL   NL  benedbr01    545000  13.208541
3        1985    ATL   NL   campri01    633333  13.358752
4        1985    ATL   NL  ceronri01    625000  13.345507
...       ...    ...  ...        ...       ...        ...
26423    2016    WAS   NL  strasst01  10400000  16.157316
26424    2016    WAS   NL  taylomi02    524000  13.169247
26425    2016    WAS   NL  treinbl01    524900  13.170963
26426    2016    WAS   NL  werthja01  21733615  16.894371
26427    2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [161]:
# Rename 'YearID' as 'SalYear'
Salary = Salary.rename(columns = {'yearID':'SalYear'})
Salary

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
...        ...    ...  ...        ...       ...        ...
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [162]:
# Let's create a copy of the df which we call "Master", which we can then use to merge the information from all the other dfs
Master = Salary
Master

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
...        ...    ...  ...        ...       ...        ...
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [163]:
# Using '.groupby' to sum across stints
Batting = Batting.groupby(['playerID','yearID']).sum()
Batting.reset_index(inplace=True)
Batting

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,2004,1,SFN,NL,11,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,2006,1,CHN,NL,45,2,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,2007,1,CHA,AL,25,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,2008,1,BOS,AL,47,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,2009,1,SEA,AL,73,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95245,zwilldu01,1914,1,CHF,FL,154,592,91,185,38,8,16,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
95246,zwilldu01,1915,1,CHF,FL,150,548,65,157,32,7,13,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
95247,zwilldu01,1916,1,CHN,NL,35,53,4,6,1,0,1,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0
95248,zychto01,2015,1,SEA,AL,13,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95249,zychto01,2016,1,SEA,AL,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [164]:
# Subset Batting data to only include seasons 1998-2006 and batters with at least 130 AB

Batting = Batting[(Batting.yearID >= 1998) & (Batting.yearID <= 2006) & (Batting.AB >= 130)].copy()
display(Batting)

# Now our data consists of 3551 rows × 22 columns

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
98,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0
100,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0
117,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0
118,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0
119,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0
94989,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0
94990,zeileto01,2004,1,NYN,NL,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0
95105,zimmery01,2006,1,WAS,NL,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0
95170,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0

In [165]:
# Calculate PA, OBP, SLG and BA in Batting data

Batting['PA'] = Batting['AB'] + Batting['BB'] + Batting['HBP'] + Batting['SH'] + Batting['SF']

Batting['OBP'] = (Batting['H'] + Batting['BB'] + Batting['HBP'])/(Batting['AB'] + Batting['BB']
                                                                  + Batting['HBP'] + Batting['SF'])

Batting['SLG'] = ((Batting['H'] - Batting['Doubles'] - Batting['Triples'] - Batting['HR'])
                  + 2*Batting['Doubles'] + 3*Batting['Triples'] + 4*Batting['HR'])/Batting['AB']

Batting['BA'] = Batting['H']/Batting['AB']

display(Batting)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA
98,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689
100,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419
117,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887
118,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727
119,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727
94989,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425
94990,zeileto01,2004,1,NYN,NL,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759
95105,zimmery01,2006,1,WAS,NL,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645
95170,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044

In [166]:
# Create another year variable to link previous season stats to next year's salary in batting data

Batting['SalYear'] = Batting['yearID'] + 1
display(Batting)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear
98,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999
100,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001
117,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999
118,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000
119,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003
94989,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004
94990,zeileto01,2004,1,NYN,NL,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759,2005
95105,zimmery01,2006,1,WAS,NL,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645,2007
95170,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007

In [167]:
# Merge Batting into our Master dataset
Master = pd.merge(Batting, Master, on=['SalYear', 'playerID'])
display(Master)

,playerID,yearID,stint,teamID_x,lgID_x,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear,teamID_y,lgID_y,salary,lnSal
0,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019
1,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538
2,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150
3,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363
4,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,NYN,NL,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323
3110,zeileto01,2001,1,NYN,NL,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323
3111,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976
3112,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511
3113,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834

# II. Building the Dataset: Player Info

In [168]:
# Read in People data retrieved from Lahman's Database
People = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 2 Content/Week 2 Assignment/People.csv")

# Read in player appearance data retrieved from Lahman's Database
Appearances = pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 2 Content/Week 2 Assignment/Appearances.csv")

In [169]:
# Extract debut year from debut date in player info data
Debut = People[['playerID','debut']].copy()
Debut['debutyr'] = Debut['debut'].astype(str).str[0:4]
Debut = Debut[['playerID','debutyr']]
display(Debut)

        playerID debutyr
0      aardsda01    2004
1      aaronha01    1954
2      aaronto01    1962
3       aasedo01    1977
4       abadan01    2001
...          ...     ...
19365   zupofr01    1957
19366  zuvelpa01    1982
19367  zuverge01    1951
19368  zwilldu01    1910
19369   zychto01    2015

[19370 rows x 2 columns]

In [170]:
# Now merge debut year into master data
Master = pd.merge(Master, Debut, on=['playerID'], how = 'left')
display(Master)

,playerID,yearID,stint,teamID_x,lgID_x,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear,teamID_y,lgID_y,salary,lnSal,debutyr
0,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997
1,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997
2,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993
3,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993
4,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,NYN,NL,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323,1989
3110,zeileto01,2001,1,NYN,NL,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323,1989
3111,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976,1989
3112,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511,1989
3113,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834,2006

In [171]:
# Calculating years of experience
Master['Exp'] = Master['yearID'] - Master['debutyr'].astype(int)
display(Master)

,playerID,yearID,stint,teamID_x,lgID_x,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear,teamID_y,lgID_y,salary,lnSal,debutyr,Exp
0,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1
1,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3
2,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5
3,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993,6
4,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,NYN,NL,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323,1989,11
3110,zeileto01,2001,1,NYN,NL,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323,1989,12
3111,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976,1989,13
3112,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511,1989,14
3113,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834,2006,0

In [172]:
# Use experience as proxy to classify players contract status as arbitration eligible or free agent
Master['Arb'] = np.where((Master['Exp'] <= 6) & (Master['Exp'] >= 3),1,0)
Master['Free'] = np.where(Master['Exp'] > 6, 1, 0)
display(Master)

,playerID,yearID,stint,teamID_x,lgID_x,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear,teamID_y,lgID_y,salary,lnSal,debutyr,Exp,Arb,Free
0,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1,0,0
1,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3,1,0
2,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5,1,0
3,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993,6,1,0
4,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993,7,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,NYN,NL,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323,1989,11,0,1
3110,zeileto01,2001,1,NYN,NL,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323,1989,12,0,1
3111,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976,1989,13,0,1
3112,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511,1989,14,0,1
3113,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834,2006,0,0,0

In [173]:
# Aggregate appearance data by stint using playerID and yearID
Appearances = Appearances.groupby(['playerID','yearID'])[['G_c','G_1b','G_2b','G_3b','G_ss','G_of','G_dh']].sum()
Appearances.reset_index(inplace=True)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh
0      aardsda01    2004    0     0     0     0     0     0   0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...
96607  zwilldu01    1915    0     3     0     0     0   148   0.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0
96609   zychto01    2015    0     0     0     0     0     0   0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0

[96612 rows x 9 columns]

In [174]:
# Find max number of appearances for each position
Appearances['Max_G'] = Appearances[["G_c","G_1b","G_2b","G_3b","G_ss","G_of","G_dh"]].max(axis=1)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0

[96612 rows x 10 columns]

In [175]:
# Create definiton to position classification process
def Position(df):
    if (df['Max_G'] == df['G_c']): return "C"
    elif (df['Max_G'] == df['G_1b']): return "1B"
    elif (df['Max_G'] == df['G_2b']): return "2B"
    elif (df['Max_G'] == df['G_3b']): return "3B"
    elif (df['Max_G'] == df['G_ss']): return "SS"
    elif (df['Max_G'] == df['G_of']): return "OF"
    elif (df['Max_G'] == df['G_dh']): return "DH"

# Apply newly created definition to appearance data as variable 'POS'
Appearances['POS'] = Appearances.apply(Position, axis = 1)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G POS
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0   C
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0   C
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0   C
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0   C
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0   C
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...  ..
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0  OF
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0  OF
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0   C
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0   C
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0   C

[96612 rows x 11 columns]

In [176]:
# Exclude non-position players (designated hitters) and keep necessary variables
Appearances = Appearances[Appearances['Max_G'] > 0]
Appearances = Appearances[['playerID','yearID','POS']]
display(Appearances)

        playerID  yearID POS
9      aaronha01    1954  OF
10     aaronha01    1955  OF
11     aaronha01    1956  OF
12     aaronha01    1957  OF
13     aaronha01    1958  OF
...          ...     ...  ..
96596  zuvelpa01    1991  3B
96605  zwilldu01    1910  OF
96606  zwilldu01    1914  OF
96607  zwilldu01    1915  OF
96608  zwilldu01    1916  OF

[55969 rows x 3 columns]

In [177]:
# Create a indicator variable for catcher and infielders (2B, 3B, SS) separately
Appearances['Catch'] = np.where(Appearances['POS'] == "C", 1, 0)
Appearances['SecB'] = np.where(Appearances['POS'] == "2B", 1, 0)
Appearances['ThirB'] = np.where(Appearances['POS'] == "3B", 1, 0)
Appearances['SS'] = np.where(Appearances['POS'] == "SS", 1, 0)
display(Appearances)

        playerID  yearID POS  Catch  SecB  ThirB  SS
9      aaronha01    1954  OF      0     0      0   0
10     aaronha01    1955  OF      0     0      0   0
11     aaronha01    1956  OF      0     0      0   0
12     aaronha01    1957  OF      0     0      0   0
13     aaronha01    1958  OF      0     0      0   0
...          ...     ...  ..    ...   ...    ...  ..
96596  zuvelpa01    1991  3B      0     0      1   0
96605  zwilldu01    1910  OF      0     0      0   0
96606  zwilldu01    1914  OF      0     0      0   0
96607  zwilldu01    1915  OF      0     0      0   0
96608  zwilldu01    1916  OF      0     0      0   0

[55969 rows x 7 columns]

In [178]:
# Merge position data into Master data
Master = pd.merge(Master, Appearances, on=['playerID','yearID'], how = 'left')
display(Master)

,playerID,yearID,stint,teamID_x,lgID_x,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA,SalYear,teamID_y,lgID_y,salary,lnSal,debutyr,Exp,Arb,Free,POS,Catch,SecB,ThirB,SS
0,abbotje01,1998,1,CHA,AL,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1,0,0,OF,0,0,0,0
1,abbotje01,2000,1,CHA,AL,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3,1,0,OF,0,0,0,0
2,abbotku01,1998,3,OAKCOL,ALNL,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5,1,0,SS,0,0,0,1
3,abbotku01,1999,1,COL,NL,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993,6,1,0,2B,0,1,0,0
4,abbotku01,2000,1,NYN,NL,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993,7,0,1,SS,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,NYN,NL,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323,1989,11,0,1,1B,0,0,0,0
3110,zeileto01,2001,1,NYN,NL,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323,1989,12,0,1,1B,0,0,0,0
3111,zeileto01,2002,1,COL,NL,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976,1989,13,0,1,3B,0,0,1,0
3112,zeileto01,2003,3,NYAMON,ALNL,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511,1989,14,0,1,3B,0,0,1,0
3113,zobribe01,2006,1,TBA,AL,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834,2006,0,0,0,SS,0,0,0,1

# III. Running Regressions

In [179]:
#Separate into pre and post Moneyball Years
Pre_MB_Data = Master[(Master.SalYear >= 1999) & (Master.SalYear <= 2003)]
Post_MB_Data = Master[(Master.SalYear >= 2004) & (Master.SalYear <= 2006)]

In [180]:
# Regression for labor market valuation of OBP, SLG and BA for seasons pre Moneyball
import statsmodels.formula.api as smf
Pre_MB_All_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_Data).fit()
Pre_MB_All_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.692
Model:                            OLS   Adj. R-squared:                  0.690
Method:                 Least Squares   F-statistic:                     391.0
Date:                Tue, 11 Aug 2026   Prob (F-statistic):               0.00
Time:                        20:02:45   Log-Likelihood:                -1855.1
No. Observations:                1753   AIC:                             3732.
Df Residuals:                    1742   BIC:                             3792.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.3410      0.165     62.841      0.000      10.018      10.664
OBP            1.5595      0.703      2.219      0.027       0.181       2.938
SLG            2.9532      0.319      9.255      0.000       2.327       3.579
BA            -2.2090      0.892     -2.478      0.013      -3.958      -0.460
PA             0.0031      0.000     27.281      0.000       0.003       0.003
Arb            1.2463      0.046     26.856      0.000       1.155       1.337
Free           1.8196      0.046     39.198      0.000       1.729       1.911
Catch          0.1168      0.054      2.181      0.029       0.012       0.222
SecB          -0.0751      0.056     -1.341      0.180      -0.185       0.035
ThirB          0.0086      0.054      0.158      0.874      -0.098       0.115
SS             0.1028      0.058      1.765      0.078      -0.011       0.217
==============================================================================
Omnibus:                       11.010   Durbin-Watson:                   1.405
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               15.168
Skew:                          -0.027   Prob(JB):                     0.000509
Kurtosis:                       3.453   Cond. No.                     2.92e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.92e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [182]:
# Here we just run each regression by taking a subset for the relevant year, but we don't print out the results.

Pre_MB_1999 = Master[(Master.SalYear == 1999)]
Val_1999_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_1999).fit()
Pre_MB_2000 = Master[(Master.SalYear == 2000)]
Val_2000_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_2000).fit()
Pre_MB_2001 = Master[(Master.SalYear == 2001)]
Val_2001_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_2001).fit()
Pre_MB_2002 = Master[(Master.SalYear == 2002)]
Val_2002_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_2002).fit()
Pre_MB_2003 = Master[(Master.SalYear == 2003)]
Val_2003_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Pre_MB_2003).fit()

In [183]:
# Make a Table for all the Pre-Moneyball regressions
from statsmodels.iolib.summary2 import summary_col
Header = ['1999-2003','1999','2000','2001','2002','2003']
Pre_Moneyball_Table = summary_col([Pre_MB_All_lm,Val_1999_lm,Val_2000_lm,Val_2001_lm,Val_2002_lm,Val_2003_lm,],\
                      regressor_order=['OBP','SLG','BA','PA','Arb','Free','Catch','SecB','ThirB','SS','Intercept'],stars=True, \
                      float_format="'%.3f'",model_names = Header)
print(Pre_Moneyball_Table)

=====================================================================================
                1999-2003      1999       2000        2001        2002        2003
-------------------------------------------------------------------------------------
OBP            '1.559'**   '1.132'     '3.160'**  '0.527'     '0.754'     '3.256'*
               ('0.703')   ('1.390')   ('1.459')  ('1.475')   ('1.838')   ('1.808')
SLG            '2.953'***  '3.552'***  '3.047'*** '3.516'***  '2.251'***  '1.866'**
               ('0.319')   ('0.608')   ('0.681')  ('0.671')   ('0.775')   ('0.872')
BA             '-2.209'**  '-3.467'*   '-2.353'   '-1.477'    '-0.192'    '-2.166'
               ('0.892')   ('1.779')   ('1.882')  ('1.993')   ('2.130')   ('2.189')
PA             '0.003'***  '0.003'***  '0.002'*** '0.003'***  '0.003'***  '0.003'***
               ('0.000')   ('0.000')   ('0.000')  ('0.000')   ('0.000')   ('0.000')
Arb            '1.246'***  '1.192'***  '1.282'*** '1.119'***  '1.281'***  '1.240'***
               ('0.046')   ('0.088')   ('0.101')  ('0.101')   ('0.115')   ('0.113')
Free           '1.820'***  '1.626'***  '1.906'*** '1.785'***  '1.933'***  '1.807'***
               ('0.046')   ('0.088')   ('0.099')  ('0.098')   ('0.119')   ('0.114')
Catch          '0.117'**   '0.029'     '0.057'    '0.168'     '0.075'     '0.274'**
               ('0.054')   ('0.101')   ('0.121')  ('0.114')   ('0.127')   ('0.131')
SecB           '-0.075'    '-0.038'    '-0.053'   '0.174'     '-0.133'    '-0.331'**
               ('0.056')   ('0.108')   ('0.123')  ('0.123')   ('0.132')   ('0.133')
ThirB          '0.009'     '0.012'     '-0.125'   '0.062'     '-0.000'    '0.118'
               ('0.054')   ('0.107')   ('0.119')  ('0.112')   ('0.130')   ('0.132')
SS             '0.103'*    '0.294'**   '0.187'    '0.057'     '-0.086'    '0.039'
               ('0.058')   ('0.115')   ('0.126')  ('0.124')   ('0.138')   ('0.143')
Intercept      '10.341'*** '10.487'*** '9.990'*** '10.234'*** '10.335'*** '10.219'***
               ('0.165')   ('0.319')   ('0.363')  ('0.347')   ('0.407')   ('0.427')
R-squared      '0.692'     '0.754'     '0.703'    '0.735'     '0.665'     '0.664'
R-squared Adj. '0.690'     '0.746'     '0.694'    '0.728'     '0.655'     '0.654'
=====================================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [184]:
# Regression for labor market valuation of OBP, SLG and BA for seasons pre Moneyball
Post_MB_All_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Post_MB_Data).fit()
Post_MB_All_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.625
Model:                            OLS   Adj. R-squared:                  0.621
Method:                 Least Squares   F-statistic:                     167.5
Date:                Tue, 11 Aug 2026   Prob (F-statistic):          2.52e-206
Time:                        20:14:07   Log-Likelihood:                -1174.4
No. Observations:                1018   AIC:                             2371.
Df Residuals:                    1007   BIC:                             2425.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.0289      0.263     38.187      0.000       9.514      10.544
OBP            5.4668      1.085      5.041      0.000       3.339       7.595
SLG            2.9302      0.477      6.141      0.000       1.994       3.866
BA            -4.6748      1.345     -3.475      0.001      -7.314      -2.035
PA             0.0029      0.000     17.314      0.000       0.003       0.003
Arb            1.0955      0.068     16.088      0.000       0.962       1.229
Free           1.6821      0.066     25.606      0.000       1.553       1.811
Catch          0.0946      0.078      1.217      0.224      -0.058       0.247
SecB          -0.0968      0.078     -1.234      0.217      -0.251       0.057
ThirB         -0.0068      0.079     -0.086      0.931      -0.162       0.149
SS             0.0380      0.087      0.435      0.663      -0.133       0.209
==============================================================================
Omnibus:                       12.597   Durbin-Watson:                   1.389
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               16.384
Skew:                           0.149   Prob(JB):                     0.000277
Kurtosis:                       3.545   Cond. No.                     3.10e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.1e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [185]:
# Here we just run each regression by taking a subset for the relevant year, but we don't print out the results.

Post_MB_2004 = Master[(Master.SalYear == 2004)]
Val_2004_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Post_MB_2004).fit()
Post_MB_2005 = Master[(Master.SalYear == 2005)]
Val_2005_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Post_MB_2005).fit()
Post_MB_2006 = Master[(Master.SalYear == 2006)]
Val_2006_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BA + PA + Arb + Free + Catch + SecB + ThirB + SS', data=Post_MB_2006).fit()

In [186]:
# Make a Table for all the Post-Moneyball regressions
Header_2 = ['2004-2006','2004','2005','2006']
Post_Moneyball_Table = summary_col([Post_MB_All_lm,Val_2004_lm,Val_2005_lm,Val_2006_lm,],\
                      regressor_order=['OBP','SLG','BA','PA','Arb','Free','Catch','SecB','ThirB','SS','Intercept'],stars=True, \
                      float_format="'%.3f'",model_names = Header_2)
print(Post_Moneyball_Table)

=============================================================
                2004-2006      2004       2005        2006
-------------------------------------------------------------
OBP            '5.467'***  '7.782'***  '4.778'**  '3.300'*
               ('1.085')   ('1.851')   ('1.932')  ('1.883')
SLG            '2.930'***  '3.158'***  '3.666'*** '2.070'**
               ('0.477')   ('0.850')   ('0.828')  ('0.819')
BA             '-4.675'*** '-8.430'*** '-4.133'*  '-1.259'
               ('1.345')   ('2.361')   ('2.284')  ('2.386')
PA             '0.003'***  '0.003'***  '0.003'*** '0.003'***
               ('0.000')   ('0.000')   ('0.000')  ('0.000')
Arb            '1.095'***  '1.045'***  '1.095'*** '1.198'***
               ('0.068')   ('0.118')   ('0.121')  ('0.118')
Free           '1.682'***  '1.535'***  '1.741'*** '1.790'***
               ('0.066')   ('0.115')   ('0.119')  ('0.110')
Catch          '0.095'     '0.086'     '0.084'    '0.143'
               ('0.078')   ('0.136')   ('0.137')  ('0.132')
SecB           '-0.097'    '-0.152'    '-0.150'   '0.025'
               ('0.078')   ('0.142')   ('0.134')  ('0.134')
ThirB          '-0.007'    '-0.173'    '0.050'    '0.074'
               ('0.079')   ('0.145')   ('0.141')  ('0.129')
SS             '0.038'     '0.160'     '-0.039'   '-0.018'
               ('0.087')   ('0.151')   ('0.154')  ('0.151')
Intercept      '10.029'*** '10.155'*** '9.894'*** '10.072'***
               ('0.263')   ('0.459')   ('0.451')  ('0.470')
R-squared      '0.625'     '0.620'     '0.633'    '0.645'
R-squared Adj. '0.621'     '0.608'     '0.621'    '0.634'
=============================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

From looking at both of these tables we can corroborate the results of Hakes and Sauer as the effect of OBP on salary gets more prevalent after the publishing of Moneyball.  We can see by the increase in coefficients in the regressions portraying how the ability to draw a walk was undervalued prior to the publication of the Moneyball story.

In [187]:
#Uncomment this cell once the assignment is complete in order to export your Master dataset
Master.to_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 2 - Moneyball and Beyond/Week 2 Content/Week 2 Assignment/Master.csv")